targets:
  - target: "default"
    update_to: "latest"
cve_urgency_levels:
  - cve_urgency_conditions:
      number_CVEs: 20
      fraction_actively_exploited_CVEs: 0.5
    deadline_days: 5
    name: "urgent"
default_deadline_days: 14
deadline_adjustments: 
  skip_weekends: True
  skip_specific_weekdays:
    - "mon"
    - "tue"
  skipped_dates:
    - "24/12"
    - "25/12"
    - "21/05"
  month_first: False
  adjust_date_earlier: False