targets:
  - target: "default"
    update_to: "latest"
cve_urgency_levels:
  - cve_urgency_conditions:
      number_CVEs: 20
      fraction_actively_exploited_CVEs: 0.5
    deadline_days: 2
    name: "urgent"
default_deadline_days: 14